name: Safety Action Build And Publish

on: [push]

env:
    DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -t pyupio/safety-v2-beta:latest .

      - name: Upload image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
             docker push pyupio/safety-v2-beta:latest
